//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Report
    {
        public int Id { get; set; }
        public int Task_id { get; set; }
        public int Comment_id { get; set; }
    
        public virtual ClientTask ClientTask { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
